// Generated by CoffeeScript 1.6.3
(function() {
  var ProcessEnvPrecompiler, fs;

  fs = require("fs");

  module.exports = ProcessEnvPrecompiler = (function() {
    ProcessEnvPrecompiler.prototype.brunchPlugin = true;

    ProcessEnvPrecompiler.prototype.searchRegEx = /\$PROCESS_ENV_(\w+)/gi;

    function ProcessEnvPrecompiler(config) {
      var conf, _ref;
      conf = ((_ref = config.plugins) != null ? _ref.process_env : void 0) || {};
      this.customSources = conf.custom_sources || [];
      this.raw = conf.raw || false;
    }

    ProcessEnvPrecompiler.prototype.includeCustomSources = function(generatedFiles) {
      var file, files, generatedFile, _i, _j, _len, _len1, _ref;
      if (!(this.customSources.length > 0)) {
        return generatedFiles;
      }
      files = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = generatedFiles.length; _i < _len; _i++) {
          file = generatedFiles[_i];
          _results.push({
            path: file.path
          });
        }
        return _results;
      })();
      for (_i = 0, _len = generatedFiles.length; _i < _len; _i++) {
        generatedFile = generatedFiles[_i];
        _ref = generatedFile.sourceFiles;
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          file = _ref[_j];
          if (file.path.indexOf(this.customSources) > -1) {
            files.push(file);
          }
        }
      }
      return files;
    };

    ProcessEnvPrecompiler.prototype.onCompile = function(generatedFiles) {
      var file, _i, _len, _ref, _results,
        _this = this;
      _ref = this.includeCustomSources(generatedFiles);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        file = _ref[_i];
        _results.push((function(file) {
          var data, result;
          data = fs.readFileSync(file.path, "utf8");
          result = data.replace(_this.searchRegEx, function(match) {
            var replacement;
            match = match.replace('$PROCESS_ENV_', '');
            if (match && process.env[match]) {
              if (_this.raw) {
                replacement = process.env[match];
              } else {
                replacement = "'" + process.env[match] + "'";
              }
            } else {
              replacement = 'undefined';
            }
            return replacement;
          });
          return fs.writeFileSync(file.path, result);
        })(file));
      }
      return _results;
    };

    return ProcessEnvPrecompiler;

  })();

}).call(this);
